name = "SimpleHypergraphs"
uuid = "7558dd50-0253-11e9-0eb7-479a738ce184"
authors = ["Bogumił Kamiński <bkamins@sgh.waw.pl>", "Przemysław Szufel <pszufe@sgh.waw.pl>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
